name: Lab1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y dotnet-sdk-7.0 python3 python3-pip fsharp
          sudo apt-get update
          sudo apt-get install mono-complete
          

  format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Format F# code with Fantomas
        run: | 
          dotnet tool install fantomas-tool --global --version "4.*"
          dotnet tool list
          fantomas src --recurse
          fantomas tests --recurse
          
      - name: Upload formatted files
        uses: actions/upload-artifact@v3
        with:
          name: formatted-src
          path: src
  
  build:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build task7
        run: |
          dotnet build src/task7/inf --configuration Release
          dotnet build src/task7/rec --configuration Release
          dotnet build src/task7/tail_rec --configuration Release
          dotnet build src/task7/module  --configuration Release
          dotnet build src/task7/map --configuration Release

      - name: Build task26
        run: |
          dotnet build src/task26/inf  --configuration Release
          dotnet build src/task26/rec  --configuration Release
          dotnet build src/task26/tail_rec  --configuration Release
          dotnet build src/task26/module  --configuration Release
          dotnet build src/task26/map --configuration Release
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: '**/bin/Release'

  task7:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run task7 applications
        run: |
          dotnet run --project src/task7/inf --configuration Release
          dotnet run --project src/task7/rec --configuration Release
          dotnet run --project src/task7/tail_rec --configuration Release
          dotnet run --project src/task7/module --configuration Release
          dotnet run --project src/task7/map --configuration Release

      - name: Run task7 tests
        run: cd tests/Task7.Tests && dotnet test

  task26:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run task26 applications
        run: |
          dotnet run --project src/task26/inf --configuration Release
          dotnet run --project src/task26/rec --configuration Release
          dotnet run --project src/task26/tail_rec --configuration Release
          dotnet run --project src/task26/module --configuration Release
          dotnet run --project src/task26/map --configuration Release
      
      - name: Run task26 tests
        run: cd tests/Task26.Tests && dotnet test

  run_python:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip3 install pylint

      - name: Run Python Lint
        run: pylint src/task7/python/task7.py src/task26/python/task26.py
      
      - name: Task 7 Python
        run: python3 src/task7/python/task7.py

      - name: Task 26 Python
        run: python3 src/task26/python/task26.py
          